#!/bin/bash

# lifconvert: convert lif file to series of tiff stacks
# uses current terminal
# Kota Miura (cmci.embl.de)        

echo "=== Lif Converter ==="
DIR=`dirname "$0"`
echo $DIR
echo "$@"
sh /g/almf/software/ij/lifcon.sh "$@"
