#!/bin/bash
# qsubIJ: does ImageJ processing in cluster via qusub command
# uses cluster qsub
# two arguments are required: macrofile full path and image file full path 
# Author: Kota Miura (miura@embl.de)        
JOBNAME="ImageJ"
WALLTIME="1:00:00"
QUENAME="clng_new"
echo "=== Imagej Processing in Cluster ==="
DIR=`dirname "$0"`
echo $DIR
arg=("$@")
echo "$@"
echo $arg 
#echo "${arg[0]}"
#echo "${arg[1]}"
logfilename="CLlog"`date +%Y%m%d`"_"`date +%H%M`".txt"
#logfilename=${HOME}/${logfilename}
logfilename="/g/almf/"`whoami`"/"${logfilename}
echo $logfilename
echo `date` > ${logfilename}
# if [ ! -f ${args[0]} ]
# then
	# echo "macro file does not exits"
	# exit 1
# else
	# echo "macro file exits"
# fi
# if [ ! -f ${args[1]} ]
# then
	# echo "image file does not exits"
	# exit 1
# fi
